# Generated by Django 5.2.4 on 2025-08-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_booking_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
