# Generated by Django 5.2.4 on 2025-08-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_is_staff_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='_is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
