# Generated by Django 5.2.4 on 2025-08-16 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser__is_staff'),
        ('rooms', '0004_booking_guests_room_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeractivity',
            name='description',
        ),
        migrations.AddField(
            model_name='customeractivity',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeractivity',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room'),
        ),
    ]
