# Generated by Django 5.2.4 on 2025-08-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customeractivity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeractivity',
            name='action',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
